#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'

#Delayed::Worker.logger = Logger.new("your_log_file.log")
Delayed::Command.new(ARGV).daemonize
