name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - 'jruby'
        rails_version:
          - '6.0'
          - '6.1'
        include:
          # Older Rails
          - ruby: '2.2'
            rails_version: '3.2'
          - ruby: '2.1'
            rails_version: '4.1'
          - ruby: '2.4'
            rails_version: '4.2'
          - ruby: '2.4'
            rails_version: '5.0'
          - ruby: '2.5'
            rails_version: '5.1'
          - ruby: '2.5'
            rails_version: '5.2'
          - ruby: 'jruby'
            rails_version: '5.2'
          # Experimental
          - ruby: 'ruby-head'
            rails_version: '6.1'
            experimental: true
          - ruby: 'jruby-head'
            rails_version: '6.1'
            experimental: true
          - ruby: '2.7'
            rails_version: 'edge'
            experimental: true
          - ruby: '3.0'
            rails_version: 'edge'
            experimental: true
          - ruby: 'jruby'
            rails_version: 'edge'
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      continue-on-error: ${{ matrix.experimental || false }}
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      continue-on-error: ${{ matrix.experimental || false }}
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
      run: bundle exec rspec
    - name: Coveralls Parallel
      continue-on-error: ${{ matrix.experimental || false }}
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.ruby }}-${{ matrix.rails_version }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
